### ISSUE TITLE
Version 1.0.0 Tracker

### ISSUE THREAD

**Issue by danthonywalker** [NeonTech/Lumberjack#1]
This issue is to track all potential changes planned for 1.0.0. Contributors are asked to open separate PRs if they fix different issues as listed.

## Publishing

- [x] Upload to ~~Maven Central~~ JCenter
- [x] Configure [Metadata Publishing](https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#metadata-publishing)
- [x] Target all (or most) Kotlin [platforms](https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#supported-platforms)
- [x] Configure [GitHub Actions](https://github.com/NeonTech/Lumberjack/actions/new) to automatically compile, test, and publish

## Code Quality

- [x] Significantly improve README documentation
- [ ] Add comprehensive KDocs (minimum have 100% public API coverage)
- [x] Improve MDC API
- [ ] Add tests

## API Changes

- [ ] Remove `DeprecatedLayout` and replace with a [`PatternLayout`](https://logging.apache.org/log4j/2.x/manual/layouts.html#PatternLayout) equivalent
